version: '3.9'

services:
    node-vsc-devcontainer:
        container_name: node-vsc-devcontainer
        build:
            context: .
        volumes:
            - type: volume
              source: node-vsc-devcontainer-shared-volume
              target: /usr/projects
        ports:
            - "8000:8000"
        secrets:
            - user_ssh_key
        command: /bin/sh -c "while sleep 1000; do :; done"
        environment:
            - NODE_ENV=development
volumes:
    node-vsc-devcontainer-shared-volume:
secrets:
    user_ssh_key:
        file: ~/.ssh/id_ed25519